@Tenant_Id = tenant1
@MultiTenant_HostAddress = http://{{Tenant_Id}}.127.0.0.1.nip.io:8086

###
# @name login
POST http://localhost:8080/realms/{{Tenant_Id}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=test-client&client_secret=test-client-secret&scope=openid

###

GET {{MultiTenant_HostAddress}}/persons/
Authorization: Bearer {{login.response.body.$.access_token}}
Accept: application/json

###
# Response
